### ISSUE TITLE
after update to 1.23.11 not run

### ISSUE THREAD

**Issue by lakusz1github** [louislam/uptime-kuma#4329]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After Non-Docker update, and run "npm run download-dist" i get errors

### 👟 Reproduction steps

```log
cd <uptime-kuma-directory>

# Update from git
git fetch --all
git checkout 1.23.11 --force

# Install dependencies and prebuilt
npm install --production
```

### 👀 Expected behavior

run w/o errors

### 😓 Actual Behavior

```shell
root@uptime:/opt/uptime-kuma# npm run download-dist

> uptime-kuma@1.23.11 download-dist
> node extra/download-dist.js

Downloading dist
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'tar'
Require stack:
- /opt/uptime-kuma/extra/download-dist.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/opt/uptime-kuma/extra/download-dist.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/uptime-kuma/extra/download-dist.js' ]
}

Node.js v18.17.1
```

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

FF

### 🐋 Docker Version

Proxmox LXC

### 🟩 NodeJS Version

18.17.1

**Comment by louislam** [comment]
a package is missing. Make sure `npm install --production` is completed.

**Comment by lakusz1github** [comment]
looks fine, no errors

**Comment by lakusz1github** [comment]
revert from snap, and try again... let us know

**Comment by CommanderStorm** [comment]
> looks fine, no errors

Closing as resolved
