### ISSUE TITLE
"Client network socket disconnected before secure TLS connection was established"

### ISSUE THREAD

**Issue by Skimige** [louislam/uptime-kuma#2860]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

This is not a bug report. I just wish to leave some words here to help other people behind.

I run uptime-kuma without Docker.

I have some HTTPS monitors, and after upgrading to v1.20.2, 2 of them are not working.

After tcpdump, I recognize that these HTTPS requests went into my local proxy which should only be used if I specified the proxy for the monitor, but now all requests are using proxy.

I now know what is wrong: I used `export` to apply proxies, as my network to GitHub directly is slow and cannot download dist from GitHub. And I restarted uptime-kuma. For some reason, when I execute `pm2 start`, environment variables about proxy are also adopted by PM2 (which is checked by `pm2 env uptime-kuma`)

After deleting and starting uptime-kuma from PM2 without these variables, the issue gets fixed.

***

Keywords

Error in log:

`res.request.res.socket.getPeerCertificate is not a function`

Error in monitor status:

`Client network socket disconnected before secure TLS connection was established`

### 🐻 Uptime-Kuma Version

1.20.2

### 💻 Operating System and Arch

Debian 11 x86_64

### 🌐 Browser

Microsoft Edge 110.0.1587.50

### 🟩 NodeJS Version

18.12.1

**Comment by b-a0** [comment]
I'm on 1.22.1 and get the same error:

```log
uptime       | 2023-07-14T17:00:22+02:00 [MONITOR] ERROR: Caught error
uptime       | 2023-07-14T17:00:22+02:00 [MONITOR] ERROR: res.request.res.socket.getPeerCertificate is not a function
```

All monitors seem to work. I do have a proxy configured in the Uptime settings, but no monitors use it as the corporate proxy is configured on the Docker host in [the file `~/.docker/config.json`](https://docs.docker.com/network/proxy/#configure-the-docker-client).

As there seems no error, can I somehow mute this to prevent log pollution?
